### ISSUE TITLE
How to find these xyz?

### ISSUE THREAD

**Issue by shimenga** [aurenex/simple-esp#2]
I want to make BedESP.

**Comment by rxznve** [comment]
Hello, @shimenga!

You need to use special programs like [WinAPIOverride](http://jacquelin.potier.free.fr/winapioverride32/) to view which OpenGL functions are called by the game. Note that WinAPIOverride does not have a monitoring file with OpenGL function declarations by default. You need to download this [file](https://github.com/aurenex/simple-esp/files/14131981/OpenGL.txt) and place it in the monitoring files folder. Or, you can try to decompile the game and study its source code.

Sincerely,
August Vishnevsky.
